{
    "date_created": " ",     
    "project_name": " ",     
    "project_path": "x",     
    "verbose": true,
    "load_to_memory": true,
    "grid_dx_in_m": 35000,          
    "grid_lat_min": 30, 
    "grid_lat_max": 65,  
    "grid_lon_min": -15,    
    "grid_lon_max": 25,     
    "synt_data": "DIS",
    "wavefield_duration": 800.0, 
    "wavefield_type": "analytic",
    "wavefield_point_force": 1.0e6,
    "wavefield_path": "x",
    "wavefield_domain": "time",
    "wavefield_sampling_rate": 0.5,
    "wavefield_filter": [0.01, 0.2],
    "wavefield_channel": "Z"
}
