{
    "date_created": " ",     
    "project_name": " ",     
    "project_path": "x",     
    "verbose": true,
    "grid_dx": 30000,            
    "grid_lat_min": 30, 
    "grid_lat_max": 65,  
    "grid_lon_min": -15,    
    "grid_lon_max": 25,     
    "synt_data": "DIS",      
    "wavefield_duration": 1800.0, 
    "wavefield_type": "analytic",
    "wavefield_point_force": 1.0e6,
    "wavefield_path": "x",
    "wavefield_sampling_rate": 1.0,
    "wavefield_filter": [0.01, 0.2],
    "wavefield_channel": "Z"
}
